# Generated by Django 5.2.4 on 2025-08-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'user profile', 'verbose_name_plural': 'user profiles'},
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['location'], name='location_idx'),
        ),
    ]
