# Generated by Django 5.2.4 on 2025-08-17 09:59

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter phone number with country code (e.g., +1234567890)', max_length=128, null=True, region=None),
        ),
    ]
