# Generated by Django 5.0.6 on 2024-07-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0003_alter_category_slug"),
        ("vendor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("vendor", "category_name"), name="unique_vendor_category"
            ),
        ),
    ]
