# Generated by Django 5.2.4 on 2025-08-16 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_remove_category_unique_vendor_slug_and_more'),
        ('vendor', '0004_openinghours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='vendor.vendor'),
        ),
    ]
