# Generated by Django 5.2.4 on 2025-08-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_category_vendor'),
        ('vendor', '0006_openinghours_vendor_open_day_of__38aa03_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fooditem',
            constraint=models.UniqueConstraint(fields=('vendor', 'food_title'), name='unique_vendor_food_title'),
        ),
    ]
