# Generated by Django 5.2.4 on 2025-08-16 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_fooditem_unique_vendor_food_title'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fooditem',
            name='unique_vendor_food_title',
        ),
    ]
