# Generated by Django 5.2.4 on 2025-08-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='country',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
