# Generated by Django 5.2.4 on 2025-08-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_tax_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='tax_type',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
