# Generated by Django 5.2.4 on 2025-08-16 20:49

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_alter_tax_tax_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=15, null=True),
        ),
    ]
