# Generated by Django 5.2.4 on 2025-08-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_alter_tax_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='category',
            field=models.CharField(blank=True, choices=[('food', 'Food'), ('service', 'Service'), ('luxury', 'Luxury')], max_length=50, null=True),
        ),
    ]
