# Generated by Django 4.2.7 on 2023-12-28 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_api', '0004_reviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
